

<? xml version="1.0" encoding ="UTF-8" ?>
<library>
<book>
<author> rr martin </author>
<title> game of thrones </title>
<price> 1222.22 </price>
</book>

<book>
<author> peter norvig </author>
<title> ai book </title>
<price> 12121.121 </price>
</book>
</library>

// DTD
<!DOCTYPE library[
<!ELEMENT library(book+)>
<!ELEMENT book(author, title, price)>
<!ELEMENT author(#PCDATA)>
<!ELEMENT title(#PCDATA)>
<!ELEMENT price(#PCDATA)>
]>

// XSD 

<? xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="https://www.w3.org/2001/XMLSchema" >
<xs:element name="library">
<xs:complexType>
<xs:sequence>
<xs:element name="book" maxOccurs="unbounded" minOccurs = "0">
<xs:complexType>
<xs:sequence>
<xs:element name="author" type="xs:string"/>
<xs:element name="title" type="xs:string" />
<xs:element name="price" type="xs:float" />
</xs:sequence>



